project_id = "vmrmvcndzrkcxwjoxplv"

[functions.fetch-news]
verify_jwt = false

[functions.fetch-bluesky]
verify_jwt = false

[functions.analyze-news]
verify_jwt = false

[functions.extract-locations]
verify_jwt = false

[functions.extract-entities]
verify_jwt = false

[functions.enrich-query]
verify_jwt = false
